apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
  labels:
    app.kubernetes.io/component: run
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: secure-server-wrkld-2
  name: secure-server-wrkld-2
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: secure-server-wrkld-2
  template:
    metadata:
      labels:
        app.kubernetes.io/component: run
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: secure-server-wrkld-2
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: secure-server-wrkld-2-from-ca
            items:
              - key: keystore.p12
                path: keystore.p12
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.health.probes.enabled="true"
            -Dserver.port="8443" -Dserver.shutdown.grace-period="24s" -Dserver.ssl.key-store="classpath:keystore/keystore.p12" -Dserver.ssl.key-store-password="password123" -Dserver.ssl.key-alias="1"
        image: dev.registry.tanzu.vmware.com/serverless/jsanin/supply-chain/tanzu-java-web-app-https-default@sha256:f6c28d2816b6a064b95da1745dde79ff87e609eef35e0d2dfe16b0abc317c519
        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/workspace/BOOT-INF/classes/keystore"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /livez
            port: 8443
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: workload
        ports:
        - containerPort: 8443
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8443
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 250Mi
        securityContext:
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    projectcontour.io/upstream-protocol.tls: "8443"
  labels:
    app.kubernetes.io/component: run
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: secure-server-wrkld-2
  name: secure-server-wrkld-2
  namespace: default
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app.kubernetes.io/component: run
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: secure-server-wrkld-2
  type: ClusterIP
