---
apiVersion: v1
kind: Secret
metadata:
  name: tap-ingress-selfsigned-root-ca
  namespace: default
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/tls
data:
  ca.crt: e30K # <-- will be filled
  tls.crt: e30K # <-- will be filled
  tls.key: e30K # <-- will be filled
