spring:
  application:
    name: tanzu-java-web-app
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
# The format used for the keystore. It could be set to JKS in case it is a JKS file
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    # The path to the keystore containing the certificate
    key-store: "classpath:keystore/secure-server-workloads.p12"
    # The password used to generate the certificate
    key-store-password: s3cure
    # The alias mapped to the certificate
    key-alias: secure-server-workloads

#HTTP port
# http:
#   port: 8080
